# Generated by Django 4.1.1 on 2022-09-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Subscribed', 'Subscribed'), ('Unsubscribed', 'Unsubscribed')], default='Subscribed', max_length=20)),
            ],
        ),
    ]
